version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 5432:5432
